language: node_js
node_js:
  - "8"
  - "10"
  - "12"
# Xenial build environment comes with MySQL 5.7
dist: xenial
services:
  - mysql
env:
  global:
    - MYSQL_HOST=localhost
    - MYSQL_PORT=3306
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
before_install:
  - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('test') where User='test'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost' WITH GRANT OPTION;FLUSH PRIVILEGES;"
  - mysql -e "GRANT SUPER ON *.* TO 'test'@'localhost' IDENTIFIED BY 'test';FLUSH PRIVILEGES;"
  
